module.exports = {
	defaultSettings: {
		prefix: '?',
		guildcolor: '',
		guildid: '',
		guildname: '',
		prune: false,
		allownsfw: false,
		audit: false,
		welcome: false,
		allowinvites: false,
		twitchmention: false,
		kickondeny: false,
		verifychannel: 'Not Set',
		auditchannel: 'Not Set',
		welcomechannel: 'Not Set',
		invitelimit: 10,
		ruleschannel: 'Not Set',
		starchannel: 'Not Set',
		twitterchannel: 'Not Set',
		twitchchannel: 'Not Set',
		birthdaychannel: 'Not Set',
		levelchannel: 'Not Set',
		staffpermission: 'Not Set',
		disabledModules: ['legacy'],
		channels: [],
		twitterwatch: [],
		nsfwblacklist: [],
	},
};
